spring:
  config:
    import: optional:secrets.properties
  application:
    name: MentalHealthSystem
  datasource:
    url: jdbc:mysql://localhost:3306/mental_health_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  jmx:
    enabled: true
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  mail:
    host: smtp.qq.com
    username: 2042837972@qq.com
    password: onqnaetsocliccjc
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  sql:
    init:
      mode: always
      schema-locations: classpath*:db/*.sql
      continue-on-error: true
      encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.cupk.entity
  global-config:
    db-config:
      id-type: auto

server:
  port: 8080
  servlet:
    context-path: /mental
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8

management:
  endpoints:
    jmx:
      exposure:
        include: "*"

upload:
  dir: D:/WorkSpace2025/WebStudy/WebStudy/mental_health_system/src/main/resources/static/upload/

deepseek:
  api:
    key: ${DEEPSEEK_API_KEY}
    url: https://api.deepseek.com/v1/chat/completions

questionnaire:
  file: classpath:questionnaires/default_questionnaire.json
  assessment:
    prompt: "根据以下问卷答案，提供一个心理健康评估报告：\n\n{{answers}}\n\n请给出综合评估，建议和改善方向。"
